### ISSUE TITLE
Is there a way to temporarily open "archive" history?

### ISSUE THREAD

**Issue by Jerry-Terrasse** [yusufaktepe/rofi-gpaste#3]
Hello, thanks for your great work!

I'm using the "archive" history as a sort of "pinned" space to store some long-term items. But every time I need those items from the archive history, I have to:

1. Invoke `rofi-gpaste`
2. Press `Alt+2` to switch to the archive history
3. Select the needed item
4. Invoke `rofi-gpaste` again
5. Press `Alt+1` to switch back to the normal history (I've forgotten this many times and ended up messing up my archive)

It's a bit cumbersome for me.

So, is there a way to just temporarily open and load something from the archive history, without affecting the currently active history?

**Comment by yusufaktepe** [comment]
I've just added an option for the `-H`, `--histories` flag. If a history name is given after this flag, it sets the initial history name.

So, basically, you need to start the script with `rofi-gpaste -H history`.

Let me know if it works for you.

_Edit:_ This won’t switch back to history until the next run, though. Since switching histories also affects the primary clipboard, I don’t think there is a reliable way to do that.

**Comment by Jerry-Terrasse** [comment]
Wow, it's perfect!
